export enum TypeCollision {
    DEFAULT = 0,
    BODY_ENEMY = 11,
    WEAPON_ENEMY = 12,
    RADIUS_ENEMY = 13,

    BODY_PLAYER = 21,
    WEAPON_PLAYER = 22,
    RADIUS_PLAYER = 23,
    RADIUS_TRAKING_PLAYER = 24,

    RADIUS_CUTTING = 30,
}